//
//  ZKMRNHP_Plugin.m
//  Zirkonium
//
//  Created by C. Ramakrishnan on 02.04.08.
//  Copyright 2008 Illposed Software. All rights reserved.
//

#import "ZKMRNHP_Plugin.h"
#import "ZKMRNHP_Device.h"


//  UUID generated by /usr/bin/uuidgen
//  CDB2D1C9-5E00-466C-AECE-F73E7259804C
#define kZirkoniumFactoryID																				\
            CFUUIDGetConstantUUIDWithBytes( NULL, 0xCD, 0xB2, 0xD1, 0xC9, 0x5E, 0x00, 0x46, 0x6C,	\
                                            0xAE, 0xCE, 0xF7, 0x3E, 0x72, 0x59, 0x80, 0x4C)
											
// #define ZKMCNDebugPrintf printf
#define ZKMCNDebugPrintf 

CFStringRef		ZKMRNHP_Plugin::CopyPlugInName() const
{
	CFStringRef theAnswer = CFSTR("de.zkm.zirkonium.plugin");
	CFRetain(theAnswer);
	return theAnswer;
}

ZKMORHP_Device*	ZKMRNHP_Plugin::CreateDevice(AudioDeviceID deviceID)
{
	return new ZKMRNHP_Device(deviceID, this);
}

//  Utility Functions

Boolean HasBundleID()
{
	CFBundleRef bundle = CFBundleGetMainBundle();
	if (!bundle) return false;
	
	CFStringRef bundleID = CFBundleGetIdentifier(bundle);
	return (NULL != bundleID);
}


Boolean IsRunningInZirkonium()
{
	CFBundleRef bundle = CFBundleGetMainBundle();
	if (!bundle) return false;
	
	CFStringRef bundleID = CFBundleGetIdentifier(bundle);
	if (!bundleID) return false;
	 
	return (kCFCompareEqualTo == CFStringCompare(CFSTR("de.zkm.Zirkonium"), bundleID, 0));
}

Boolean IsZirkoniumReachable()
{
	ZKMCNDebugPrintf("IsZirkoniumReachable?\n"); 
	CFMessagePortRef zirkoniumServerPort = CFMessagePortCreateRemote(NULL, CFSTR("ZirkoniumHALServerPort"));
	if (NULL == zirkoniumServerPort) {
		ZKMCNDebugPrintf("NO!\n"); 	
		return false;
	}
	
	CFMessagePortInvalidate(zirkoniumServerPort);
	CFRelease(zirkoniumServerPort);
	ZKMCNDebugPrintf("YES!\n"); 		
	return true;
}


extern "C" void*
New_ZKMRNHP_PlugIn(CFAllocatorRef /*inAllocator*/, CFUUIDRef inRequestedTypeUUID) 
{
	void*	theAnswer = NULL;
	// Don't create the plug-in if I'm inside Zirkonium
//	if (!HasBundleID()) return NULL;
	if (IsRunningInZirkonium()) return theAnswer;
	if (!IsZirkoniumReachable()) return theAnswer;
	
	if(CFEqual(inRequestedTypeUUID, kAudioHardwarePlugInTypeID))
	{
		ZKMRNHP_Plugin*	thePlugIn = new ZKMRNHP_Plugin(inRequestedTypeUUID);
		thePlugIn->Retain();
		theAnswer = thePlugIn->GetInterface();
	}
	
	return theAnswer;
}